HOST                = "127.0.0.1"
USER                = "root"
PASSWORD            = "atul@123"
DATABASE            = "user_db"
FIREBASE_USER       = "https://bookmyauto-test.firebaseio.com/users/"
FIREBASE_DRIVER     = "https://bookmyauto-test.firebaseio.com/drivers/"
